name: 'Maven Package'

on: [ 'push', 'pull_request' ]

jobs:
    build:
        if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
            - name: Build with Maven
              run: mvn -B package --file pom.xml