# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package to Unnamed Repo and github packages

on:
    release:
        types: [created]
jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - name: Set up Java for publishing to unnamed repo
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  server-id: unnamed-releases
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
            - name: Publish to unnamed repo
              run: mvn --batch-mode deploy
              env:
                  MAVEN_USERNAME: ${{ secrets.USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.TOKEN }}